<?php
declare(strict_types=1);

chdir(__DIR__ . '/..');
require_once __DIR__ . '/../php/session_security.php';
AppSessionStart();
require_once __DIR__ . '/../php/db_connection.php';
require_once __DIR__ . '/../php/admin_auth_helper.php';
require_once __DIR__ . '/../php/activity_logger.php';
AdminRequireLogin();
header('Cache-Control: no-store, no-cache, must-revalidate, max-age=0');

if (empty($_SESSION['payout_admin_csrf'])) $_SESSION['payout_admin_csrf'] = bin2hex(random_bytes(32));
$csrfToken = (string)$_SESSION['payout_admin_csrf'];

function payoutEnsureTable(PDO $pdo): void {
    $pdo->exec("CREATE TABLE IF NOT EXISTS provider_payouts (
      payout_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT, booking_domain VARCHAR(20) NOT NULL,
      booking_id INT NOT NULL, booking_reference VARCHAR(20) NOT NULL, provider_type VARCHAR(30) NOT NULL,
      provider_id INT NULL, provider_key VARCHAR(80) NOT NULL, provider_name VARCHAR(190) NOT NULL,
      gross_amount DECIMAL(12,2) NOT NULL DEFAULT 0, status VARCHAR(20) NOT NULL DEFAULT 'pending',
      approved_by_admin_id INT NULL, approved_at DATETIME NULL, settlement_method VARCHAR(40) NULL,
      settlement_reference VARCHAR(120) NULL, settlement_note VARCHAR(500) NULL,
      settled_by_admin_id INT NULL, settled_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
      PRIMARY KEY (payout_id), UNIQUE KEY uq_provider_booking (booking_domain,booking_id,provider_key),
      KEY idx_payout_status (status), KEY idx_payout_provider (provider_type,provider_id), KEY idx_payout_settled (settled_at)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}
function payoutSyncLedger(PDO $pdo): void {
    $pdo->exec("UPDATE provider_payouts p JOIN bookings b ON b.booking_id=p.booking_id AND p.booking_domain=LOWER(b.booking_type)
      LEFT JOIN operators o ON o.operator_id=b.operator_id LEFT JOIN tour_guides tg ON tg.guide_id=b.guide_id LEFT JOIN boats bt ON bt.boat_id=b.boat_id
      SET p.provider_type=CASE LOWER(b.booking_type) WHEN 'package' THEN 'operator' WHEN 'tourguide' THEN 'tourguide' ELSE 'boat' END,
        p.provider_id=CASE LOWER(b.booking_type) WHEN 'package' THEN b.operator_id WHEN 'tourguide' THEN b.guide_id ELSE b.boat_id END,
        p.provider_key=CONCAT(CASE LOWER(b.booking_type) WHEN 'package' THEN 'operator' WHEN 'tourguide' THEN 'tourguide' ELSE 'boat' END,':',COALESCE(CASE LOWER(b.booking_type) WHEN 'package' THEN b.operator_id WHEN 'tourguide' THEN b.guide_id ELSE b.boat_id END,0)),
        p.provider_name=COALESCE(NULLIF(TRIM(CASE LOWER(b.booking_type) WHEN 'package' THEN o.fullname WHEN 'tourguide' THEN tg.fullname ELSE bt.name END),''),p.provider_name),
        p.booking_reference=COALESCE(NULLIF(b.booking_reference,''),p.booking_reference),p.gross_amount=GREATEST(COALESCE(b.payment_amount,0),0),p.updated_at=NOW()
      WHERE p.status='pending'");
    $pdo->exec("INSERT INTO provider_payouts
      (booking_domain,booking_id,booking_reference,provider_type,provider_id,provider_key,provider_name,gross_amount,status)
      SELECT LOWER(b.booking_type),b.booking_id,COALESCE(NULLIF(b.booking_reference,''),CONCAT('BK-',b.booking_id)),
        CASE LOWER(b.booking_type) WHEN 'package' THEN 'operator' WHEN 'tourguide' THEN 'tourguide' ELSE 'boat' END,
        CASE LOWER(b.booking_type) WHEN 'package' THEN b.operator_id WHEN 'tourguide' THEN b.guide_id ELSE b.boat_id END,
        CONCAT(CASE LOWER(b.booking_type) WHEN 'package' THEN 'operator' WHEN 'tourguide' THEN 'tourguide' ELSE 'boat' END,':',COALESCE(CASE LOWER(b.booking_type) WHEN 'package' THEN b.operator_id WHEN 'tourguide' THEN b.guide_id ELSE b.boat_id END,0)),
        COALESCE(NULLIF(TRIM(CASE LOWER(b.booking_type) WHEN 'package' THEN o.fullname WHEN 'tourguide' THEN tg.fullname ELSE bt.name END),''),
          CASE LOWER(b.booking_type) WHEN 'package' THEN 'Unassigned tour operator' WHEN 'tourguide' THEN 'Unassigned tour guide' ELSE COALESCE(NULLIF(TRIM(b.preferred_resource),''),'Unassigned boat') END),
        GREATEST(COALESCE(b.payment_amount,0),0),'pending'
      FROM bookings b LEFT JOIN operators o ON o.operator_id=b.operator_id
      LEFT JOIN tour_guides tg ON tg.guide_id=b.guide_id LEFT JOIN boats bt ON bt.boat_id=b.boat_id
      WHERE COALESCE(b.payment_amount,0)>0 AND NOT EXISTS (SELECT 1 FROM provider_payouts existing WHERE existing.booking_domain=LOWER(b.booking_type) AND existing.booking_id=b.booking_id)
      ON DUPLICATE KEY UPDATE booking_reference=VALUES(booking_reference),provider_name=VALUES(provider_name),
        gross_amount=IF(provider_payouts.status='pending',VALUES(gross_amount),provider_payouts.gross_amount),updated_at=NOW()");
    $pdo->exec("UPDATE provider_payouts p JOIN hotel_room_bookings hb ON hb.hotel_booking_id=p.booking_id AND p.booking_domain='hotel'
      LEFT JOIN hotel_resorts hr ON hr.hotel_resort_id=hb.hotel_resort_id
      SET p.provider_id=hb.hotel_resort_id,p.provider_key=CONCAT('hotel:',COALESCE(hb.hotel_resort_id,0)),
        p.provider_name=COALESCE(NULLIF(TRIM(hr.name),''),p.provider_name),p.booking_reference=COALESCE(NULLIF(hb.booking_reference,''),p.booking_reference),
        p.gross_amount=GREATEST(COALESCE(hb.amount_paid,0),0),p.updated_at=NOW() WHERE p.status='pending'");
    $pdo->exec("INSERT INTO provider_payouts
      (booking_domain,booking_id,booking_reference,provider_type,provider_id,provider_key,provider_name,gross_amount,status)
      SELECT 'hotel',hb.hotel_booking_id,COALESCE(NULLIF(hb.booking_reference,''),CONCAT('HR-',hb.hotel_booking_id)),
        'hotel',hb.hotel_resort_id,CONCAT('hotel:',COALESCE(hb.hotel_resort_id,0)),
        COALESCE(NULLIF(TRIM(hr.name),''),'Unassigned hotel / resort'),GREATEST(COALESCE(hb.amount_paid,0),0),'pending'
      FROM hotel_room_bookings hb LEFT JOIN hotel_resorts hr ON hr.hotel_resort_id=hb.hotel_resort_id
      WHERE COALESCE(hb.amount_paid,0)>0 AND NOT EXISTS (SELECT 1 FROM provider_payouts existing WHERE existing.booking_domain='hotel' AND existing.booking_id=hb.hotel_booking_id)
      ON DUPLICATE KEY UPDATE booking_reference=VALUES(booking_reference),provider_name=VALUES(provider_name),
        gross_amount=IF(provider_payouts.status='pending',VALUES(gross_amount),provider_payouts.gross_amount),updated_at=NOW()");
}
function payoutMoney(float $amount): string { return '₱'.number_format($amount,2); }
function payoutLabel(string $value): string { return match(strtolower(trim($value))){
  'package'=>'Tour Package','tourguide'=>'Tour Guide','boat'=>'Boat','hotel'=>'Hotel / Resort','operator'=>'Tour Operator',
  'bank_transfer'=>'Bank Transfer','e_wallet'=>'E-wallet',default=>ucwords(str_replace(['_','-'],' ',$value))}; }
function payoutCsvSafe(string $value): string { return preg_match('/^\s*[=+\-@]/u',$value)?"'".$value:$value; }
function payoutRedirect(string $type,string $message): never { $_SESSION['payout_notice']=['type'=>$type,'message'=>$message];header('Location: adearningsdisbursements.php');exit; }
/** @return array{applicable:bool,ready:bool,amount:float,note:string} */
function payoutRetentionAssessment(array $record): array {
  $completion=strtolower(trim((string)($record['completion_status']??'')));
  $policy=strtolower(trim((string)($record['refund_policy']??'')));
  $requestStatus=strtolower(trim((string)($record['cancellation_status']??$record['request_status']??'')));
  $refundStatus=strtolower(trim((string)($record['request_refund_status']??$record['refund_status']??'')));
  $paid=max(0.0,(float)($record['amount_paid']??$record['gross_amount']??0));
  $retained=min($paid,max(0.0,(float)($record['non_refundable_amount']??0)));
  $refundable=max(0.0,(float)($record['refundable_amount']??0));
  $applicable=$completion==='cancelled'&&in_array($policy,['partial_refund','deposit_non_refundable'],true)&&$retained>0.009;
  $refundComplete=$refundable<=0.009||in_array($refundStatus,['completed','refunded','succeeded','not_applicable'],true);
  $ready=$applicable&&$requestStatus==='completed'&&$refundComplete;
  $note=$applicable
    ? 'Late-cancellation policy: '.payoutMoney($retained).' was retained as the non-refundable portion (up to 20% of the booking total).'.($ready?' The cancellation and required refund are complete, so this retained amount may be settled to the provider.':' Settlement remains locked until the cancellation and required refund are completed.')
    : '';
  return ['applicable'=>$applicable,'ready'=>$ready,'amount'=>$applicable?$retained:0.0,'note'=>$note];
}

payoutEnsureTable($pdo);
payoutSyncLedger($pdo);

if ($_SERVER['REQUEST_METHOD']==='POST') {
  if(!hash_equals($csrfToken,(string)($_POST['csrf_token']??'')))payoutRedirect('error','Your session token expired. Please try again.');
  $action=strtolower((string)($_POST['action']??''));$payoutId=(int)($_POST['payout_id']??0);
  $adminId=(int)($_SESSION['admin_id']??0);$adminName=(string)($_SESSION['admin_name']??$_SESSION['username']??'Administrator');
  try {
    $pdo->beginTransaction();
    $stmt=$pdo->prepare("SELECT p.*,CASE WHEN p.booking_domain='hotel' THEN LOWER(COALESCE(hb.booking_status,'')) ELSE LOWER(COALESCE(b.is_complete,'')) END completion_status
      FROM provider_payouts p LEFT JOIN bookings b ON p.booking_domain<>'hotel' AND b.booking_id=p.booking_id
      LEFT JOIN hotel_room_bookings hb ON p.booking_domain='hotel' AND hb.hotel_booking_id=p.booking_id WHERE p.payout_id=? LIMIT 1 FOR UPDATE");
    $stmt->execute([$payoutId]);$payout=$stmt->fetch(PDO::FETCH_ASSOC);if(!$payout)throw new RuntimeException('The payout record could not be found.');
    if($action==='settle'){
      if(!in_array((string)$payout['status'],['pending','approved'],true))throw new RuntimeException('Only an unsettled payout can be settled.');
      $settlementAmount=(float)$payout['gross_amount'];$completion=(string)$payout['completion_status'];
      if($completion!=='completed'){
        $cancellationDomain=(string)$payout['booking_domain']==='hotel'?'hotel':'tour';
        $cancellationStmt=$pdo->prepare("SELECT request_status cancellation_status,refund_status request_refund_status,refund_policy,refundable_amount,non_refundable_amount,amount_paid FROM booking_cancellation_requests WHERE booking_domain=? AND booking_id=? ORDER BY cancellation_request_id DESC LIMIT 1");
        $cancellationStmt->execute([$cancellationDomain,(int)$payout['booking_id']]);
        $cancellation=$cancellationStmt->fetch(PDO::FETCH_ASSOC)?:[];$cancellation['completion_status']=$completion;
        $retention=payoutRetentionAssessment($cancellation);
        if(!$retention['ready'])throw new RuntimeException('This payout is locked until the booking or eligible late-cancellation refund workflow is completed.');
        $settlementAmount=(float)$retention['amount'];
      }
      if($settlementAmount<=0.009)throw new RuntimeException('This booking has no provider amount available to settle.');
      $method=strtolower(trim((string)($_POST['settlement_method']??'')));$reference=trim((string)($_POST['settlement_reference']??''));$note=trim((string)($_POST['settlement_note']??''));
      if(!in_array($method,['bank_transfer','e_wallet','cash','other'],true))throw new RuntimeException('Select a valid disbursement method.');
      if($reference===''||mb_strlen($reference)>120)throw new RuntimeException('Enter a valid transfer or acknowledgment reference.');
      if(mb_strlen($note)>500)throw new RuntimeException('The settlement note must not exceed 500 characters.');
      $update=$pdo->prepare("UPDATE provider_payouts SET gross_amount=?,status='settled',approved_by_admin_id=COALESCE(approved_by_admin_id,?),approved_at=COALESCE(approved_at,NOW()),settlement_method=?,settlement_reference=?,settlement_note=?,settled_by_admin_id=?,settled_at=NOW() WHERE payout_id=? AND status IN ('pending','approved')");
      $update->execute([$settlementAmount,$adminId,$method,$reference,$note!==''?$note:null,$adminId,$payoutId]);if($update->rowCount()!==1)throw new RuntimeException('The payout changed before settlement could be recorded.');$pdo->commit();
      logActivity($pdo,'Admin',$adminId,$adminName,'Settled Provider Payout','Recorded '.payoutMoney($settlementAmount).' payout for booking '.$payout['booking_reference'].' to '.$payout['provider_name'].'.','Earnings & Disbursements',$payoutId);
      payoutRedirect('success','Payout '.$payout['booking_reference'].' was recorded as settled.');
    }
    throw new RuntimeException('Unsupported payout action.');
  }catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();payoutRedirect('error',$error->getMessage());}
}

$tourRows=$pdo->query("SELECT p.*,t.full_name guest_name,t.email guest_email,b.booking_date service_date,b.created_at booking_created,b.payment_method,b.status booking_status,b.is_complete completion_status,
 b.location,b.package_name,b.pax,b.phone_number,b.num_adults,b.num_children,b.jump_off_port,b.tour_type,b.tour_range,b.grand_total booking_total,b.payment_amount amount_paid,b.remaining_balance,
 (SELECT br.status FROM booking_refunds br WHERE br.cancellation_request_id=cr.cancellation_request_id ORDER BY br.booking_refund_id DESC LIMIT 1) refund_transaction_status,
 (SELECT COALESCE(SUM(br.amount_minor),0) FROM booking_refunds br WHERE br.cancellation_request_id=cr.cancellation_request_id AND br.status='succeeded') refund_amount_minor,
 cr.cancellation_request_id,cr.request_status cancellation_status,cr.refund_status request_refund_status,cr.refund_policy,cr.refundable_amount,cr.non_refundable_amount,
 CASE WHEN LOWER(COALESCE(b.is_complete,'')) IN ('cancelled','declined') OR LOWER(COALESCE(b.status,''))='declined' THEN 1 ELSE 0 END is_excluded
 FROM provider_payouts p JOIN bookings b ON b.booking_id=p.booking_id AND p.booking_domain<>'hotel' LEFT JOIN tourist t ON t.tourist_id=b.tourist_id
 LEFT JOIN booking_cancellation_requests cr ON cr.cancellation_request_id=(SELECT cr2.cancellation_request_id FROM booking_cancellation_requests cr2 WHERE cr2.booking_id=p.booking_id AND LOWER(cr2.booking_domain)='tour' ORDER BY cr2.cancellation_request_id DESC LIMIT 1)")->fetchAll(PDO::FETCH_ASSOC);
$hotelRows=$pdo->query("SELECT p.*,CONCAT_WS(' ',hb.first_name,hb.last_name) guest_name,hb.email guest_email,hb.checkout_date service_date,hb.created_at booking_created,
 COALESCE(hb.balance_payment_method,hb.payment_type) payment_method,hb.booking_status,hb.booking_status completion_status,
 hr.island location,hr.name package_name,(hb.adults+hb.children) pax,hb.phone_number,hb.adults num_adults,hb.children num_children,'' jump_off_port,'accommodation' tour_type,
 CONCAT(DATE_FORMAT(hb.checkin_date,'%b %e, %Y'),' - ',DATE_FORMAT(hb.checkout_date,'%b %e, %Y')) tour_range,hb.total_amount booking_total,hb.amount_paid,hb.remaining_balance,
 (SELECT br.status FROM booking_refunds br WHERE br.cancellation_request_id=cr.cancellation_request_id ORDER BY br.booking_refund_id DESC LIMIT 1) refund_transaction_status,
 (SELECT COALESCE(SUM(br.amount_minor),0) FROM booking_refunds br WHERE br.cancellation_request_id=cr.cancellation_request_id AND br.status='succeeded') refund_amount_minor,
 cr.cancellation_request_id,cr.request_status cancellation_status,cr.refund_status request_refund_status,cr.refund_policy,cr.refundable_amount,cr.non_refundable_amount,
 CASE WHEN LOWER(COALESCE(hb.booking_status,'')) IN ('cancelled','declined','no-show') THEN 1 ELSE 0 END is_excluded
 FROM provider_payouts p JOIN hotel_room_bookings hb ON hb.hotel_booking_id=p.booking_id AND p.booking_domain='hotel' LEFT JOIN hotel_resorts hr ON hr.hotel_resort_id=hb.hotel_resort_id
 LEFT JOIN booking_cancellation_requests cr ON cr.cancellation_request_id=(SELECT cr2.cancellation_request_id FROM booking_cancellation_requests cr2 WHERE cr2.booking_id=p.booking_id AND LOWER(cr2.booking_domain)='hotel' ORDER BY cr2.cancellation_request_id DESC LIMIT 1)")->fetchAll(PDO::FETCH_ASSOC);
$allRows=array_merge($tourRows,$hotelRows);
$syncPayoutAmount=$pdo->prepare("UPDATE provider_payouts SET gross_amount=?,updated_at=NOW() WHERE payout_id=? AND status='pending'");
foreach($allRows as &$row){
 $rawRefund=strtolower(trim((string)($row['refund_transaction_status']?:$row['request_refund_status']?:'')));
 $row['refund_status']=$rawRefund!==''?$rawRefund:((int)$row['is_excluded']===1?'not_started':'not_applicable');
 $completion=strtolower((string)$row['completion_status']);$retention=payoutRetentionAssessment($row);
 $row['retention_applicable']=$retention['applicable'];$row['retention_ready']=$retention['ready'];$row['payout_note']=$retention['note'];
 $calculatedAmount=$completion==='cancelled'?(float)$retention['amount']:((int)$row['is_excluded']===1?0.0:max(0.0,(float)$row['amount_paid']));
 $row['payout_amount']=(string)$row['status']==='settled'?(float)$row['gross_amount']:$calculatedAmount;
 $row['workflow_status']=(string)$row['status']==='settled'?'settled':($retention['ready']?'available':($retention['applicable']?'pending':((int)$row['is_excluded']===1?'excluded':($completion==='completed'?'available':'pending'))));
 if((string)$row['status']==='pending'&&abs((float)$row['gross_amount']-$calculatedAmount)>0.009){$syncPayoutAmount->execute([$calculatedAmount,(int)$row['payout_id']]);$row['gross_amount']=$calculatedAmount;}
}unset($row);
usort($allRows,fn(array $a,array $b):int=>strtotime((string)$b['booking_created'])<=>strtotime((string)$a['booking_created']));
$search=trim((string)($_GET['search']??''));$statusFilter=strtolower((string)($_GET['status']??'all'));$typeFilter=strtolower((string)($_GET['type']??'all'));
$stakeholderFilter=strtolower((string)($_GET['stakeholder']??'all'));$providerFilter=trim((string)($_GET['provider']??'all'));
if(!in_array($statusFilter,['all','pending','available','settled','excluded'],true))$statusFilter='all';
if(!in_array($typeFilter,['all','operator','tourguide','boat','hotel'],true))$typeFilter='all';
$providerDirectory=[];foreach($allRows as $row){$providerDirectory[(string)$row['provider_key']]=['key'=>(string)$row['provider_key'],'name'=>(string)$row['provider_name'],'type'=>strtolower((string)$row['provider_type'])];}
uasort($providerDirectory,static fn(array $a,array $b):int=>[$a['type'],$a['name']]<=>[$b['type'],$b['name']]);
if(!in_array($stakeholderFilter,['all','operator','tourguide','boat','hotel'],true))$stakeholderFilter='all';
if($providerFilter!=='all'&&!isset($providerDirectory[$providerFilter]))$providerFilter='all';
if($stakeholderFilter==='all'||($providerFilter!=='all'&&$providerDirectory[$providerFilter]['type']!==$stakeholderFilter))$providerFilter='all';
$filteredRows=array_values(array_filter($allRows,static function(array $row)use($search,$statusFilter,$typeFilter,$stakeholderFilter,$providerFilter):bool{
 if($statusFilter!=='all'&&$row['workflow_status']!==$statusFilter)return false;if($typeFilter!=='all'&&strtolower((string)$row['provider_type'])!==$typeFilter)return false;
 if($stakeholderFilter!=='all'&&strtolower((string)$row['provider_type'])!==$stakeholderFilter)return false;if($providerFilter!=='all'&&(string)$row['provider_key']!==$providerFilter)return false;
 return $search===''||str_contains(strtolower(implode(' ',[$row['booking_reference'],$row['provider_name'],$row['guest_name']])),strtolower($search));}));
if(($_GET['export']??'')==='csv'){
 header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="itour-provider-payouts-'.date('Y-m-d').'.csv"');$out=fopen('php://output','wb');fwrite($out,"\xEF\xBB\xBF");
 fputcsv($out,['iTour Mercedes — Provider Payout Ledger']);fputcsv($out,['Generated',date('F j, Y g:i A')]);fputcsv($out,[]);fputcsv($out,['Booking Reference','Provider','Provider Type','Guest','Service Date','Payment Method','Amount (PHP)','Payout Status','Authorized At','Settled At','Settlement Reference']);
 foreach($filteredRows as $row)fputcsv($out,[payoutCsvSafe((string)$row['booking_reference']),payoutCsvSafe((string)$row['provider_name']),payoutLabel((string)$row['provider_type']),payoutCsvSafe((string)$row['guest_name']),(string)$row['service_date'],payoutLabel((string)$row['payment_method']),number_format((float)$row['payout_amount'],2,'.',''),payoutLabel((string)$row['workflow_status']),(string)$row['approved_at'],(string)$row['settled_at'],payoutCsvSafe((string)$row['settlement_reference'])]);fclose($out);exit;
}
$totals=['pending'=>0.0,'available'=>0.0,'settled'=>0.0,'excluded'=>0.0];$counts=['pending'=>0,'available'=>0,'settled'=>0,'excluded'=>0];$providers=[];
foreach($allRows as $row){$state=(string)$row['workflow_status'];$amount=(float)$row['payout_amount'];$totals[$state]+=$amount;$counts[$state]++;if($state==='excluded')continue;$key=(string)$row['provider_key'];
 if(!isset($providers[$key]))$providers[$key]=['name'=>$row['provider_name'],'type'=>$row['provider_type'],'pending'=>0.0,'available'=>0.0,'settled'=>0.0,'bookings'=>0];$providers[$key][$state]+=$amount;$providers[$key]['bookings']++;}
uasort($providers,fn($a,$b)=>(($b['pending']+$b['available'])<=>($a['pending']+$a['available'])));
$totalCollected=array_sum(array_map(fn($r)=>(float)$r['amount_paid'],$allRows));$outstanding=$totals['pending']+$totals['available'];
$monthKeys=[];$monthLabels=[];$collectionMap=[];$settledMap=[];$cursor=(new DateTimeImmutable('first day of -5 months'))->setTime(0,0);
for($i=0;$i<6;$i++){$k=$cursor->format('Y-m');$monthKeys[]=$k;$monthLabels[]=$cursor->format('M');$cursor=$cursor->modify('+1 month');}
foreach($allRows as $row){$k=substr((string)$row['booking_created'],0,7);if(in_array($k,$monthKeys,true))$collectionMap[$k]=($collectionMap[$k]??0)+(float)$row['amount_paid'];}
foreach($pdo->query("SELECT DATE_FORMAT(settled_at,'%Y-%m') month_key,SUM(gross_amount) amount FROM provider_payouts WHERE status='settled' AND settled_at>=DATE_FORMAT(CURRENT_DATE-INTERVAL 5 MONTH,'%Y-%m-01') GROUP BY month_key")->fetchAll(PDO::FETCH_ASSOC) as $row)$settledMap[(string)$row['month_key']]=(float)$row['amount'];
$chartCollections=array_map(fn($k)=>$collectionMap[$k]??0,$monthKeys);$chartSettled=array_map(fn($k)=>$settledMap[$k]??0,$monthKeys);
$pageRecords=array_map(static fn(array $row):array=>['provider_key'=>(string)$row['provider_key'],'provider_type'=>strtolower((string)$row['provider_type']),'provider_name'=>(string)$row['provider_name'],'state'=>(string)$row['workflow_status'],'payout'=>(float)$row['payout_amount'],'collected'=>(float)$row['amount_paid'],'booking_month'=>substr((string)$row['booking_created'],0,7),'settled_month'=>!empty($row['settled_at'])?substr((string)$row['settled_at'],0,7):''],$allRows);
$notice=$_SESSION['payout_notice']??null;unset($_SESSION['payout_notice']);
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Earnings & Disbursements | iTour Mercedes Admin</title><link rel="icon" type="image/png" href="img/newlogo.png"><link rel="stylesheet" href="styles/admin_panel_theme.css"><link rel="stylesheet" href="styles/adearningsdisbursements.css?v=11"></head><body>
<div class="admin-container"><?php include __DIR__.'/admin_sidebar.php'; ?><main class="main-content payout-main">
<header class="admin-header admin-page-header"><div class="admin-header-left admin-page-title"><span class="admin-page-title-icon"><svg viewBox="0 0 24 24"><path d="M4 6.5h14a2 2 0 0 1 2 2V19H4a2 2 0 0 1-2-2V6.5a2 2 0 0 1 2-2h12"/><path d="M20 11h-5a2 2 0 0 0 0 4h5M15 13h.01"/></svg></span><div class="admin-page-title-copy"><h2>Earnings & Disbursements</h2><p class="admin-header-subtitle">Central PayMongo collections and controlled provider settlements</p></div></div><div class="admin-header-right payout-header-actions"><div class="page-scope-filter" aria-label="Filter the earnings workspace"><span class="scope-filter-icon"><svg viewBox="0 0 24 24"><path d="M4 6h16M7 12h10M10 18h4"/></svg></span><label><span>Stakeholder</span><select id="pageStakeholderFilter"><option value="all" <?= $stakeholderFilter==='all'?'selected':'' ?>>All stakeholders</option><option value="operator" <?= $stakeholderFilter==='operator'?'selected':'' ?>>Tour operators</option><option value="hotel" <?= $stakeholderFilter==='hotel'?'selected':'' ?>>Hotels / resorts</option><option value="tourguide" <?= $stakeholderFilter==='tourguide'?'selected':'' ?>>Tour guides</option><option value="boat" <?= $stakeholderFilter==='boat'?'selected':'' ?>>Boats</option></select></label><span class="scope-filter-arrow">Then</span><label><span>Specific recipient</span><select id="pageProviderFilter"><option value="all">All providers</option><?php foreach($providerDirectory as $providerOption):?><option value="<?= htmlspecialchars($providerOption['key']) ?>" data-provider-type="<?= htmlspecialchars($providerOption['type']) ?>" <?= $providerFilter===$providerOption['key']?'selected':'' ?>><?= htmlspecialchars($providerOption['name']) ?></option><?php endforeach;?></select></label><button type="button" class="scope-filter-reset" id="pageScopeReset" title="Show all stakeholders" <?= $stakeholderFilter==='all'&&$providerFilter==='all'?'hidden':'' ?>>Reset</button></div><a class="payout-export" id="payoutExport" href="?<?= htmlspecialchars(http_build_query(array_merge($_GET,['export'=>'csv']))) ?>"><svg viewBox="0 0 24 24"><path d="M12 3v12m0 0 4-4m-4 4-4-4M4 17v3h16v-3"/></svg>Export ledger</a></div></header>
<section class="payout-workspace">
<section class="payout-metrics" aria-label="Payout summary"><?php $metricCards=[['Collected funds',$totalCollected,'All recorded booking payments','collected','M4 19V9m5 10V5m5 14v-7m5 7V3'],['Pending payouts',$totals['pending'],$counts['pending'].' bookings awaiting completion','pending','M12 7v5l3 2M21 12a9 9 0 1 1-9-9'],['Available payouts',$totals['available'],$counts['available'].' completed bookings ready to settle','available','m8 12 2.6 2.6L16.5 9M12 3a9 9 0 1 0 9 9'],['Settled payouts',$totals['settled'],$counts['settled'].' completed disbursements','settled','m7 12 3 3 7-7M12 3a9 9 0 1 0 9 9']];foreach($metricCards as [$label,$value,$noteText,$tone,$path]):?><article class="payout-metric <?= $tone ?>" data-page-metric="<?= $tone ?>"><div class="metric-icon"><svg viewBox="0 0 24 24"><path d="<?= $path ?>"/></svg></div><div class="metric-content"><span><?= $label ?></span><strong><?= payoutMoney((float)$value) ?></strong><small><?= htmlspecialchars($noteText) ?></small><div class="metric-trend"><span class="trend-change neutral" data-metric-trend><i></i><b>0.0%</b><em>vs previous month</em></span><svg class="trend-spark" viewBox="0 0 82 28" aria-hidden="true"><polyline data-trend-line points="2,14 18,14 34,14 50,14 66,14 80,14"/><circle data-trend-point cx="80" cy="14" r="2.2"/></svg></div></div></article><?php endforeach;?></section>
<section class="payout-insights"><article class="payout-panel trend-panel"><header><div><span>6-MONTH CASH FLOW</span><h3>Collections and settlements</h3></div><div class="chart-legend"><i class="collections"></i>Collected <i class="settlements"></i>Settled</div></header><div class="payout-chart"><canvas id="payoutTrend" aria-label="Collections and settlements chart"></canvas></div></article><article class="payout-panel exposure-panel"><header><div><span>OUTSTANDING LIABILITY</span><h3>Provider payout exposure</h3><p>Share of total funds still owed</p></div><div class="exposure-total-card"><span>Total outstanding</span><strong id="exposureTotal"><?= payoutMoney($outstanding) ?></strong><small id="exposureProviderCount">Across providers</small></div></header><div class="exposure-list" id="exposureList"><?php $providerExposures=array_map(fn($p)=>(float)$p['pending']+(float)$p['available'],$providers);$maxExposure=max(array_merge([1.0],array_values($providerExposures)));foreach(array_slice($providers,0,5,true) as $provider):$due=(float)$provider['pending']+(float)$provider['available'];?><div class="exposure-row"><div><span class="provider-mark <?= htmlspecialchars((string)$provider['type']) ?>"><?= htmlspecialchars(strtoupper(substr((string)$provider['name'],0,1))) ?></span><p><strong><?= htmlspecialchars((string)$provider['name']) ?></strong><small><?= payoutLabel((string)$provider['type']) ?> · <?= (int)$provider['bookings'] ?> bookings</small></p></div><b><?= payoutMoney($due) ?></b><span class="exposure-track"><i style="width:<?= number_format(($due/$maxExposure)*100,1,'.','') ?>%"></i></span></div><?php endforeach;if(!$providers):?><div class="compact-empty">No provider balances yet.</div><?php endif;?></div></article></section>
<section class="payout-panel provider-panel"><header class="panel-title"><div><span>PROVIDER BALANCES</span><h3>Amounts to payout by recipient</h3></div></header><div class="provider-table-wrap"><table class="provider-table"><thead><tr><th>Provider</th><th class="right">Awaiting completion</th><th class="right">Available to settle</th><th class="right">Settled</th><th class="right">Outstanding</th></tr></thead><tbody id="providerBalanceBody"><?php foreach($providers as $provider):$due=(float)$provider['pending']+(float)$provider['available'];?><tr><td><div class="provider-cell"><span class="provider-mark <?= htmlspecialchars((string)$provider['type']) ?>"><?= htmlspecialchars(strtoupper(substr((string)$provider['name'],0,1))) ?></span><div><strong><?= htmlspecialchars((string)$provider['name']) ?></strong><small><?= payoutLabel((string)$provider['type']) ?></small></div></div></td><td class="right muted-money"><?= payoutMoney((float)$provider['pending']) ?></td><td class="right available-money"><?= payoutMoney((float)$provider['available']) ?></td><td class="right settled-money"><?= payoutMoney((float)$provider['settled']) ?></td><td class="right"><strong><?= payoutMoney($due) ?></strong></td></tr><?php endforeach;if(!$providers):?><tr><td colspan="5"><div class="table-empty">No provider payout balances are available.</div></td></tr><?php endif;?></tbody></table></div></section>
<section class="payout-panel ledger-panel"><header class="ledger-head"><div><span>BOOKING PAYOUT LEDGER</span><h3>All booking payments</h3><p>Each row remains traceable from collection through provider settlement.</p></div><nav class="status-tabs" aria-label="Payout ledger views"><?php foreach(['all'=>'All','pending'=>'Pending','available'=>'Available','settled'=>'Settled'] as $key=>$label):$query=array_filter(['search'=>$search,'type'=>$typeFilter==='all'?null:$typeFilter,'status'=>$key==='all'?null:$key]);?><a class="<?= $statusFilter===$key?'active':'' ?>" data-ledger-status="<?= $key ?>" href="?<?= htmlspecialchars(http_build_query($query)) ?>"><?= $label ?><span><?= $key==='all'?count($allRows):$counts[$key] ?></span></a><?php endforeach;?></nav></header>
<form class="ledger-filters" id="ledgerFilters" method="get"><label class="search-field"><input type="text" role="searchbox" name="search" value="<?= htmlspecialchars($search) ?>" placeholder="Search booking, provider, or guest"></label><label><span>Status</span><select name="status"><?php foreach(['all'=>'All statuses','pending'=>'Pending completion','available'=>'Available to settle','settled'=>'Settled','excluded'=>'Not payable'] as $key=>$label):?><option value="<?= $key ?>" <?= $statusFilter===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label><label><span>Provider</span><select name="type"><?php foreach(['all'=>'All providers','operator'=>'Tour operators','tourguide'=>'Tour guides','boat'=>'Boats','hotel'=>'Hotels / resorts'] as $key=>$label):?><option value="<?= $key ?>" <?= $typeFilter===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label><button class="filter-submit" type="submit">Apply filters</button><a class="filter-reset" data-ledger-reset href="adearningsdisbursements.php" <?= $search===''&&$statusFilter==='all'&&$typeFilter==='all'?'hidden':'' ?>>Reset</a></form>
<div class="ledger-table-wrap"><table class="ledger-table"><thead><tr><th>Booking / Guest</th><th>Provider</th><th>Service</th><th>Booking status</th><th>Payment</th><th class="right">Amount</th><th>Refund status</th><th>Payout status</th><th>Action</th></tr></thead><tbody>
<?php foreach($allRows as $row):
  $state=(string)$row['workflow_status'];$bookingStatus=strtolower((string)$row['booking_status']);$completion=strtolower((string)$row['completion_status']);$refundStatus=(string)$row['refund_status'];
  $displayBookingStatus=in_array($completion,['completed','cancelled','declined'],true)?$completion:$bookingStatus;
  $refundLabel=match($refundStatus){'not_applicable'=>'No refund','not_started'=>'Not started','succeeded','completed'=>'Refunded','pending','processing','initiating'=>'Refund processing','failed'=>'Refund failed',default=>payoutLabel($refundStatus)};
  $refundTone=match($refundStatus){'succeeded','completed'=>'success','pending','processing','initiating'=>'pending','failed'=>'danger','not_started'=>'warning',default=>'neutral'};
  $refundAmount=((float)($row['refund_amount_minor']??0))/100;if($refundAmount<=0)$refundAmount=(float)($row['refundable_amount']??0);
  $payoutStatusLabel=match($state){'pending'=>(!empty($row['retention_applicable'])?'Cancellation settlement pending':'Pending completion'),'available'=>(!empty($row['retention_applicable'])?'Retention available':'Available to settle'),'settled'=>'Settled',default=>'Not payable'};
  $detail=['booking'=>$row['booking_reference'],'guest'=>$row['guest_name'],'provider'=>$row['provider_name'],'provider_type'=>payoutLabel((string)$row['provider_type']),'service'=>payoutLabel((string)$row['booking_domain']),'service_date'=>!empty($row['service_date'])?date('F j, Y',strtotime((string)$row['service_date'])):'Date unavailable','booking_status'=>payoutLabel($bookingStatus),'completion_status'=>$completion==='uncomplete'?'Not completed':payoutLabel($completion),'payment_method'=>payoutLabel((string)$row['payment_method']),'amount'=>payoutMoney((float)$row['payout_amount']),'amount_paid'=>payoutMoney((float)$row['amount_paid']),'refund_status'=>$refundLabel,'refund_amount'=>payoutMoney($refundAmount),'retained_amount'=>payoutMoney((float)($row['non_refundable_amount']??0)),'payout_note'=>$row['payout_note']??'','retention_applicable'=>!empty($row['retention_applicable']),'cancellation_status'=>payoutLabel((string)($row['cancellation_status']??'')),'payout_status'=>$payoutStatusLabel,'settlement_reference'=>$row['settlement_reference']??''];
  $bookingDetail=['reference'=>$row['booking_reference'],'guest'=>$row['guest_name'],'email'=>$row['guest_email']??'','phone'=>$row['phone_number']??'','service'=>payoutLabel((string)$row['booking_domain']),'service_name'=>$row['package_name']?:$row['provider_name'],'service_date'=>!empty($row['service_date'])?date('F j, Y',strtotime((string)$row['service_date'])):'Date unavailable','date_range'=>$row['tour_range']??'','location'=>$row['location']??'','jump_off'=>$row['jump_off_port']??'','tour_type'=>payoutLabel((string)($row['tour_type']??'')),'pax'=>(int)($row['pax']??0),'adults'=>(int)($row['num_adults']??0),'children'=>(int)($row['num_children']??0),'status'=>payoutLabel($displayBookingStatus),'booking_status'=>payoutLabel($bookingStatus),'completion'=>$completion==='uncomplete'?'Not completed':payoutLabel($completion),'total'=>payoutMoney((float)($row['booking_total']??0)),'paid'=>payoutMoney((float)($row['amount_paid']??0)),'refund_amount'=>payoutMoney($refundAmount),'provider_payout'=>payoutMoney((float)$row['payout_amount']),'balance'=>payoutMoney((float)($row['remaining_balance']??0)),'payment_method'=>payoutLabel((string)$row['payment_method']),'refund_status'=>$refundLabel,'payout_status'=>$payoutStatusLabel,'payout_note'=>$row['payout_note']??'','retention_applicable'=>!empty($row['retention_applicable'])];
?>
<tr data-ledger-row data-state="<?= htmlspecialchars($state) ?>" data-provider-type="<?= htmlspecialchars(strtolower((string)$row['provider_type'])) ?>" data-provider-key="<?= htmlspecialchars((string)$row['provider_key']) ?>" data-search="<?= htmlspecialchars(strtolower(implode(' ',[(string)$row['booking_reference'],(string)$row['provider_name'],(string)$row['guest_name']])),ENT_QUOTES) ?>" data-payout-amount="<?= htmlspecialchars(number_format((float)$row['payout_amount'],2,'.','')) ?>"><td><div class="booking-cell"><strong><?= htmlspecialchars((string)$row['booking_reference']) ?></strong><span><?= htmlspecialchars((string)$row['guest_name']) ?></span></div></td><td><div class="provider-cell compact"><span class="provider-mark <?= htmlspecialchars((string)$row['provider_type']) ?>"><?= htmlspecialchars(strtoupper(substr((string)$row['provider_name'],0,1))) ?></span><div><strong><?= htmlspecialchars((string)$row['provider_name']) ?></strong><small><?= payoutLabel((string)$row['provider_type']) ?></small></div></div></td><td><strong><?= payoutLabel((string)$row['booking_domain']) ?></strong><span class="cell-sub"><?= !empty($row['service_date'])?date('M j, Y',strtotime((string)$row['service_date'])):'Date unavailable' ?></span></td>
<td><div class="booking-state"><span class="record-state <?= htmlspecialchars($displayBookingStatus) ?>"><?= payoutLabel($displayBookingStatus) ?></span></div></td>
<td><strong><?= payoutLabel((string)$row['payment_method']) ?></strong><span class="cell-sub">Funds received</span></td><td class="right amount-cell"><strong><?= payoutMoney((float)$row['payout_amount']) ?></strong><?php if(!empty($row['retention_applicable'])):?><small class="amount-note">Late-cancel retained</small><?php endif;?></td>
<td><span class="refund-state <?= $refundTone ?>"><i></i><?= $refundLabel ?></span><?php if(!empty($row['cancellation_status'])):?><small class="status-detail">Cancellation: <?= payoutLabel((string)$row['cancellation_status']) ?></small><?php endif;?></td>
<td><span class="payout-status <?= $state ?>"><i></i><?= htmlspecialchars($payoutStatusLabel) ?></span><?php if($state==='settled'):?><small class="status-detail"><?= date('M j, Y',strtotime((string)$row['settled_at'])) ?> · <?= htmlspecialchars((string)$row['settlement_reference']) ?></small><?php elseif(!empty($row['retention_applicable'])):?><small class="status-detail"><?= !empty($row['retention_ready'])?'Completed late-cancellation retention':'Awaiting completed cancellation/refund' ?></small><?php elseif($state==='excluded'):?><small class="status-detail">Booking <?= payoutLabel($completion) ?></small><?php endif;?></td>
<td class="action-cell"><div class="action-menu"><button class="action-menu-toggle" type="button" aria-expanded="false" aria-label="Open actions for <?= htmlspecialchars((string)$row['booking_reference']) ?>"><svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.5"/><circle cx="12" cy="12" r="1.5"/><circle cx="19" cy="12" r="1.5"/></svg></button><div class="action-popover" hidden>
  <button type="button" data-payout-details='<?= htmlspecialchars(json_encode($detail,JSON_HEX_APOS|JSON_HEX_QUOT),ENT_QUOTES) ?>'><svg viewBox="0 0 24 24"><path d="M3 12s3.5-6 9-6 9 6 9 6-3.5 6-9 6-9-6-9-6Z"/><circle cx="12" cy="12" r="2.5"/></svg>View payout details</button>
  <button type="button" data-booking-details='<?= htmlspecialchars(json_encode($bookingDetail,JSON_HEX_APOS|JSON_HEX_QUOT),ENT_QUOTES) ?>'><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg>View booking details</button>
  <button type="button" data-copy-reference="<?= htmlspecialchars((string)$row['booking_reference']) ?>"><svg viewBox="0 0 24 24"><rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/></svg>Copy booking reference</button>
  <?php if($state==='available'):?><button type="button" class="menu-settle" data-settle='<?= htmlspecialchars(json_encode(['id'=>(int)$row['payout_id'],'reference'=>$row['booking_reference'],'provider'=>$row['provider_name'],'amount'=>payoutMoney((float)$row['payout_amount'])],JSON_HEX_APOS|JSON_HEX_QUOT),ENT_QUOTES) ?>'><svg viewBox="0 0 24 24"><path d="M4 7h16v12H4zM7 11h10M7 15h6"/></svg>Settle payout</button><?php endif;?>
  <?php if($state==='settled'):?><button type="button" data-receipt='<?= htmlspecialchars(json_encode(['booking'=>$row['booking_reference'],'provider'=>$row['provider_name'],'amount'=>payoutMoney((float)$row['payout_amount']),'method'=>payoutLabel((string)$row['settlement_method']),'reference'=>$row['settlement_reference'],'note'=>$row['settlement_note'],'settled'=>date('F j, Y · g:i A',strtotime((string)$row['settled_at']))],JSON_HEX_APOS|JSON_HEX_QUOT),ENT_QUOTES) ?>'><svg viewBox="0 0 24 24"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6"/></svg>View settlement record</button><?php endif;?>
  <?php if((int)($row['cancellation_request_id']??0)>0):?><a class="refund-tool" href="adpaymenttransactions.php?view=refunds&amp;cancellation_request_id=<?= (int)$row['cancellation_request_id'] ?>"><svg viewBox="0 0 24 24"><path d="M4 10h12a4 4 0 0 1 0 8H8"/><path d="m8 6-4 4 4 4"/></svg>Open refund record</a><?php endif;?>
</div></div></td></tr>
<?php endforeach;?><tr id="ledgerEmptyRow" <?= $allRows?'hidden':'' ?>><td colspan="9"><div class="table-empty"><strong>No payout records found</strong><span>Try changing the filters or search terms.</span></div></td></tr></tbody></table></div><footer class="ledger-footer"><span id="ledgerResultCount">Showing <?= count($filteredRows) ?> of <?= count($allRows) ?> booking payment records</span><span>Filtered payout total <strong id="ledgerFilteredTotal"><?= payoutMoney(array_sum(array_map(fn($r)=>(float)$r['payout_amount'],$filteredRows))) ?></strong></span></footer></section></section></main></div>
<div class="payout-modal" id="settlementModal" aria-hidden="true"><div class="modal-backdrop" data-close-modal></div><section role="dialog" aria-modal="true"><header><div><span class="modal-icon"><svg viewBox="0 0 24 24"><path d="M4 7h16v12H4zM7 11h10M7 15h6"/></svg></span><div><small>RECORD DISBURSEMENT</small><h3>Settle provider payout</h3><p>Record the completed transfer for the audit trail.</p></div></div><button type="button" data-close-modal>×</button></header><form method="post" id="settlementForm"><input type="hidden" name="csrf_token" value="<?= htmlspecialchars($csrfToken) ?>"><input type="hidden" name="action" value="settle"><input type="hidden" name="payout_id" id="settlementPayoutId"><div class="settlement-summary"><div><span>Booking</span><strong id="settlementBooking">—</strong></div><div><span>Recipient</span><strong id="settlementProvider">—</strong></div><div><span>Amount to settle</span><strong id="settlementAmount">—</strong></div></div><label><span>Disbursement method</span><select name="settlement_method" required><option value="" selected disabled>Select transfer method</option><option value="bank_transfer">Bank transfer</option><option value="e_wallet">E-wallet</option><option value="cash">Cash acknowledgment</option><option value="other">Other verified method</option></select></label><label><span>Transfer / acknowledgment reference</span><input type="text" name="settlement_reference" maxlength="120" required placeholder="e.g. TXN-2026-00124"><small>Required for reconciliation and audit history.</small></label><label><span>Internal note <em>Optional</em></span><textarea name="settlement_note" maxlength="500" rows="3" placeholder="Add settlement details or recipient confirmation"></textarea></label><div class="modal-warning"><svg viewBox="0 0 24 24"><path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v5M12 17h.01"/></svg><p>Submitting this form authorizes and records the payout as settled.</p></div><footer><button type="button" class="modal-cancel" data-close-modal>Cancel</button><button type="submit" class="modal-confirm">Settle payout</button></footer></form></section></div>
<div class="payout-drawer" id="payoutDetailDrawer" aria-hidden="true"><div class="drawer-backdrop" data-close-drawer></div><aside role="dialog" aria-modal="true" aria-labelledby="payoutDrawerTitle"><header><div><span class="drawer-icon"><svg viewBox="0 0 24 24"><path d="M4 5h16v14H4zM8 9h8M8 13h5"/></svg></span><div><small>BOOKING PAYOUT</small><h3 id="payoutDrawerTitle">Ledger record details</h3><p>Booking, refund, and disbursement context</p></div></div><button type="button" data-close-drawer aria-label="Close payout details">×</button></header><div class="drawer-content" id="payoutDetailBody"></div><footer><button type="button" class="drawer-close-button" data-close-drawer>Close</button></footer></aside></div>
<div class="payout-drawer" id="bookingDetailDrawer" aria-hidden="true"><div class="drawer-backdrop" data-close-drawer></div><aside role="dialog" aria-modal="true" aria-labelledby="bookingDrawerTitle"><header><div><span class="drawer-icon booking"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="16" rx="2"/><path d="M8 3v4M16 3v4M3 10h18"/></svg></span><div><small>BOOKING RECORD</small><h3 id="bookingDrawerTitle">Booking details</h3><p>Complete reservation and payment information</p></div></div><button type="button" data-close-drawer aria-label="Close booking details">×</button></header><div class="drawer-content" id="bookingDetailBody"></div><footer><button type="button" class="drawer-close-button" data-close-drawer>Close</button></footer></aside></div>
<div class="payout-drawer" id="settlementRecordDrawer" aria-hidden="true"><div class="drawer-backdrop" data-close-drawer></div><aside role="dialog" aria-modal="true" aria-labelledby="settlementRecordTitle"><header><div><span class="drawer-icon"><svg viewBox="0 0 24 24"><path d="M6 3h12v18l-3-2-3 2-3-2-3 2V3Z"/><path d="M9 8h6M9 12h6"/></svg></span><div><small>SETTLEMENT RECORD</small><h3 id="settlementRecordTitle">Payout settlement</h3><p>Recorded provider disbursement</p></div></div><button type="button" data-close-drawer aria-label="Close settlement record">×</button></header><div class="drawer-content" id="receiptBody"></div><footer><button type="button" class="drawer-close-button" data-close-drawer>Close</button></footer></aside></div>
<script>window.payoutPageData=<?= json_encode(['labels'=>$monthLabels,'monthKeys'=>$monthKeys,'collections'=>$chartCollections,'settled'=>$chartSettled,'records'=>$pageRecords,'stakeholder'=>$stakeholderFilter,'provider'=>$providerFilter,'notice'=>$notice],JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?>;</script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="js/adearningsdisbursements.js?v=6"></script></body></html>
